using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TetgenDll;

namespace Tetgen_examples.Writers
{
    public static class ObjWriter
    {
        public static void SaveToObj(String filename, Point3D[] points, Face[] faces)
        {
            using (StreamWriter file = File.CreateText(filename))
            {
                file.WriteLine("# WaveFront *.obj file (generated by SilverHorn)\r\n");
                foreach (var vertex in points)
                {
                    if (vertex != null)
                    {
                        var x = vertex.GetX().ToString().Replace(',', '.');
                        var y = vertex.GetY().ToString().Replace(',', '.');
                        var z = vertex.GetZ().ToString().Replace(',', '.');
                        file.WriteLine("v {0} {1} {2}", x, y, z);
                    }
                }
                file.WriteLine("# {0} vertices\r\n", points.Length);

                foreach (var face in faces)
                {
                    foreach (var poly in face.GetPolygons())
                    {
                        file.Write("f ");
                        foreach (var index in poly.GetIndexes())
                        {
                            file.Write("{0} ", index);
                        }
                        file.WriteLine();
                    }
                }
                file.WriteLine("# {0} faces\r\n", faces.Length);
            }
        }
    }
}
